# Generated by Django 2.2 on 2019-04-22 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_ad_status',
            },
        ),
        migrations.CreateModel(
            name='Adtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_ad_type',
            },
        ),
        migrations.CreateModel(
            name='Defaultshippingaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('body_html', models.CharField(max_length=15000)),
                ('body_text', models.CharField(max_length=5000)),
                ('from_address', models.CharField(max_length=100)),
                ('bcc_address', models.CharField(max_length=100)),
                ('em_cd', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'user_email',
            },
        ),
        migrations.CreateModel(
            name='Emailstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_email_status',
            },
        ),
        migrations.CreateModel(
            name='Emailtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_email_type',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_subscriber', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_string', models.CharField(blank=True, max_length=50, null=True)),
                ('email_verification_string_signed', models.CharField(blank=True, max_length=200, null=True)),
                ('email_unsubscribed', models.BooleanField(default=False)),
                ('email_unsubscribe_string', models.CharField(max_length=50, null=True, unique=True)),
                ('email_unsubscribe_string_signed', models.CharField(max_length=200, null=True, unique=True)),
                ('reset_password_string', models.CharField(blank=True, max_length=50, null=True)),
                ('reset_password_string_signed', models.CharField(blank=True, max_length=200, null=True)),
                ('mb_cd', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('stripe_customer_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('use_default_shipping_and_payment_info', models.BooleanField(default=False)),
                ('default_shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Defaultshippingaddress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email_unsubscribed', models.BooleanField(default=False)),
                ('email_unsubscribe_string', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email_unsubscribe_string_signed', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('prospect_comment', models.CharField(blank=True, max_length=5000, null=True)),
                ('swa_comment', models.CharField(blank=True, max_length=5000, null=True)),
                ('pr_cd', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_date_time', models.DateTimeField()),
                ('converted_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Termsofuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('version_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('publication_date_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_terms_of_use_version',
            },
        ),
        migrations.CreateModel(
            name='Emailunsubscribereasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_longer_want_to_receive', models.BooleanField(default=False)),
                ('never_signed_up', models.BooleanField(default=False)),
                ('inappropriate', models.BooleanField(default=False)),
                ('spam', models.BooleanField(default=False)),
                ('other', models.CharField(blank=True, max_length=5000, null=True)),
                ('created_date_time', models.DateTimeField()),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Member')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Prospect')),
            ],
        ),
        migrations.CreateModel(
            name='Emailsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date_time', models.DateTimeField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Email')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Member')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Prospect')),
            ],
            options={
                'db_table': 'user_email_sent',
            },
        ),
        migrations.AddField(
            model_name='email',
            name='email_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Emailstatus'),
        ),
        migrations.AddField(
            model_name='email',
            name='email_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Emailtype'),
        ),
        migrations.CreateModel(
            name='Chatmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email_address', models.CharField(blank=True, max_length=254, null=True)),
                ('message', models.CharField(blank=True, max_length=5000, null=True)),
                ('created_date_time', models.DateTimeField()),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Member')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Prospect')),
            ],
            options={
                'db_table': 'user_chat_message',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignid', models.CharField(blank=True, max_length=100, null=True)),
                ('adgroupid', models.CharField(blank=True, max_length=100, null=True)),
                ('adid', models.CharField(blank=True, max_length=100, null=True)),
                ('final_url', models.CharField(blank=True, max_length=100, null=True)),
                ('headline_1', models.CharField(blank=True, max_length=30, null=True)),
                ('headline_2', models.CharField(blank=True, max_length=30, null=True)),
                ('headline_3', models.CharField(blank=True, max_length=30, null=True)),
                ('description_1', models.CharField(blank=True, max_length=90, null=True)),
                ('description_2', models.CharField(blank=True, max_length=90, null=True)),
                ('final_url_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('ad_cd', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ad_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Adstatus')),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Adtype')),
            ],
            options={
                'db_table': 'user_ad',
            },
        ),
        migrations.CreateModel(
            name='Membertermsofuseversionagreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_date_time', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Member')),
                ('termsofuseversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Termsofuse')),
            ],
            options={
                'db_table': 'user_member_terms_of_use_version_agreed',
                'unique_together': {('member', 'termsofuseversion')},
            },
        ),
    ]
