# Generated by Django 4.2.16 on 2025-12-19 20:30

from django.db import migrations


def update_email_addresses(apps, schema_editor):
    """
    Update email addresses from contact@startupwebapp.com to bart+startupwebapp@mosaicmeshai.com
    Remove BCC addresses from all emails
    Update references in email body text
    """
    Email = apps.get_model('user', 'Email')

    # Update all 4 Email templates
    for email_id in [1, 2, 3, 4]:
        try:
            email = Email.objects.get(id=email_id)

            # Update from_address with display name
            if email.from_address in ['contact@startupwebapp.com', 'bart+startupwebapp@mosaicmeshai.com']:
                email.from_address = 'StartUpWebApp <bart+startupwebapp@mosaicmeshai.com>'

            # Remove BCC address
            if email.bcc_address in ['contact@startupwebapp.com', 'bart+startupwebapp@mosaicmeshai.com', '']:
                email.bcc_address = ''

            # Update body_text - replace email references (handles both old and intermediate states)
            email.body_text = email.body_text.replace('contact@startupwebapp.com', 'bart+startupwebapp@mosaicmeshai.com')

            # Update body_html - replace email references
            email.body_html = email.body_html.replace('contact@startupwebapp.com', 'bart+startupwebapp@mosaicmeshai.com')

            # Remove PAYMENT INFORMATION line for order confirmations (IDs 1 and 2)
            # Stripe Checkout Sessions don't save payment info (card details are None)
            if email_id in [1, 2]:
                email.body_text = email.body_text.replace(
                    'PAYMENT INFORMATION {short_line_break}{payment_information} {line_break}',
                    ''
                )
                email.body_html = email.body_html.replace(
                    'PAYMENT INFORMATION {short_line_break}{payment_information} {line_break}',
                    ''
                )

            email.save()

        except Email.DoesNotExist:
            # Email template doesn't exist, skip
            pass


def reverse_email_addresses(apps, schema_editor):
    """
    Reverse migration - restore original contact@startupwebapp.com addresses
    """
    Email = apps.get_model('user', 'Email')

    for email_id in [1, 2, 3, 4]:
        try:
            email = Email.objects.get(id=email_id)

            # Restore from_address
            if email.from_address == 'StartUpWebApp <bart+startupwebapp@mosaicmeshai.com>':
                email.from_address = 'contact@startupwebapp.com'

            # Restore BCC address
            if email.bcc_address == '':
                email.bcc_address = 'contact@startupwebapp.com'

            # Restore PAYMENT INFORMATION line for order confirmations (IDs 1 and 2)
            if email_id in [1, 2]:
                # Insert PAYMENT INFORMATION before SHIPPING ADDRESS
                email.body_text = email.body_text.replace(
                    'SHIPPING ADDRESS {short_line_break}',
                    'PAYMENT INFORMATION {short_line_break}{payment_information} {line_break}SHIPPING ADDRESS {short_line_break}'
                )
                email.body_html = email.body_html.replace(
                    'SHIPPING ADDRESS {short_line_break}',
                    'PAYMENT INFORMATION {short_line_break}{payment_information} {line_break}SHIPPING ADDRESS {short_line_break}'
                )

            # Restore body_text
            if 'bart+startupwebapp@mosaicmeshai.com' in email.body_text:
                email.body_text = email.body_text.replace(
                    'bart+startupwebapp@mosaicmeshai.com',
                    'contact@startupwebapp.com'
                )

            # Restore body_html
            if 'bart+startupwebapp@mosaicmeshai.com' in email.body_html:
                email.body_html = email.body_html.replace(
                    'bart+startupwebapp@mosaicmeshai.com',
                    'contact@startupwebapp.com'
                )

            email.save()

        except Email.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_seed_user_data'),
    ]

    operations = [
        migrations.RunPython(update_email_addresses, reverse_email_addresses),
    ]
