# Generated by Django 4.2.16 on 2025-12-11 00:07
# Data migration to update email addresses from contact@startupwebapp.com to bart+startupwebapp@mosaicmeshai.com

from django.db import migrations


def update_email_addresses(apps, schema_editor):
    """
    Update existing email templates to use new email address and remove BCC.
    Updates:
    - from_address: contact@startupwebapp.com -> bart+startupwebapp@mosaicmeshai.com
    - bcc_address: contact@startupwebapp.com -> '' (empty string)
    - body_text: Update contact email references in message body
    """
    # Skip during test runs
    db_name = schema_editor.connection.settings_dict.get('NAME', '')
    if 'memory' in db_name.lower() or db_name.startswith('test_'):
        return

    Email = apps.get_model('user', 'Email')

    # Update order confirmation email for Members (id=1)
    try:
        email = Email.objects.get(id=1)
        email.from_address = 'bart+startupwebapp@mosaicmeshai.com'
        email.bcc_address = ''
        # Update body_text to replace contact email reference
        if 'contact@startupwebapp.com' in email.body_text:
            email.body_text = email.body_text.replace(
                'contact@startupwebapp.com',
                'bart+startupwebapp@mosaicmeshai.com'
            )
        email.save()
    except Email.DoesNotExist:
        pass  # Email template doesn't exist yet, will be created by seed data migration

    # Update order confirmation email for Prospects (id=2)
    try:
        email = Email.objects.get(id=2)
        email.from_address = 'bart+startupwebapp@mosaicmeshai.com'
        email.bcc_address = ''
        # Update body_text to replace contact email reference
        if 'contact@startupwebapp.com' in email.body_text:
            email.body_text = email.body_text.replace(
                'contact@startupwebapp.com',
                'bart+startupwebapp@mosaicmeshai.com'
            )
        email.save()
    except Email.DoesNotExist:
        pass  # Email template doesn't exist yet, will be created by seed data migration


def reverse_email_addresses(apps, schema_editor):
    """
    Reverse the email address changes (for rollback).
    """
    # Skip during test runs
    db_name = schema_editor.connection.settings_dict.get('NAME', '')
    if 'memory' in db_name.lower() or db_name.startswith('test_'):
        return

    Email = apps.get_model('user', 'Email')

    # Revert order confirmation email for Members (id=1)
    try:
        email = Email.objects.get(id=1)
        email.from_address = 'contact@startupwebapp.com'
        email.bcc_address = 'contact@startupwebapp.com'
        # Revert body_text
        if 'bart+startupwebapp@mosaicmeshai.com' in email.body_text:
            email.body_text = email.body_text.replace(
                'bart+startupwebapp@mosaicmeshai.com',
                'contact@startupwebapp.com'
            )
        email.save()
    except Email.DoesNotExist:
        pass

    # Revert order confirmation email for Prospects (id=2)
    try:
        email = Email.objects.get(id=2)
        email.from_address = 'contact@startupwebapp.com'
        email.bcc_address = 'contact@startupwebapp.com'
        # Revert body_text
        if 'bart+startupwebapp@mosaicmeshai.com' in email.body_text:
            email.body_text = email.body_text.replace(
                'bart+startupwebapp@mosaicmeshai.com',
                'contact@startupwebapp.com'
            )
        email.save()
    except Email.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_seed_user_data'),
    ]

    operations = [
        migrations.RunPython(update_email_addresses, reverse_email_addresses),
    ]
