# Generated by Django 5.2.9 on 2026-01-22 21:48
# Fix member and prospect email template body_text which was cleared by previous migration

from django.db import migrations


def fix_email_templates(apps, schema_editor):
    """
    Fix the order confirmation email templates for both members and prospects.
    The previous migration (0004_remove_discount_from_email_templates) incorrectly
    cleared the body_text for these emails.
    This migration restores them without the discount_information line.
    """
    Email = apps.get_model('user', 'Email')

    # Fix Member email template (ID=1)
    try:
        member_email = Email.objects.get(id=1, em_cd='gvREoqen93ffZsmBIc8zl')
        member_email.body_text = (
            'Hi {recipient_first_name}, {line_break}'
            'Thank you for your order! {line_break}'
            'ORDER INFORMATION {short_line_break}{order_information} {short_line_break}'
            'View your order here: {ENVIRONMENT_DOMAIN}/account/order?identifier={identifier}&em_cd={em_cd}&mb_cd={mb_cd} {line_break}'
            'PRODUCTS {short_line_break}{product_information} {line_break}'
            'SHIPPING METHOD {short_line_break}{shipping_information} {line_break}'
            'ORDER TOTAL {short_line_break}{order_total_information} {line_break}'
            'SHIPPING ADDRESS {short_line_break}{shipping_address_information} {line_break}'
            'BILLING ADDRESS {short_line_break}{billing_address_information} {line_break}'
            'PAYMENT INFORMATION {short_line_break}{payment_information} {line_break}'
            'Note: If you did NOT place an order at {ENVIRONMENT_DOMAIN}, do not click on the link. '
            'Instead, please forward this notification to contact@startupwebapp.com and let us know '
            'that you did not place this order and we\'ll dig in further to figure out what is going on. {line_break}'
            'We\'ll send you further emails with updates on your order along with shipping tracking '
            'information once it\'s available. {line_break}'
            'Thank you for being part of the StartUp Web App community! {line_break}'
            'By placing this order you agreed to the StartUpWebApp.com Terms of Sale: '
            '{ENVIRONMENT_DOMAIN}/terms-of-sale {line_break}'
            '© 2018 StartUp Web App LLC, All rights reserved.'
        )
        member_email.save()
        print(f"Fixed member email template: {member_email.em_cd}")
    except Email.DoesNotExist:
        print("Member email template not found, skipping fix.")

    # Fix Prospect email template (ID=2)
    try:
        prospect_email = Email.objects.get(id=2, em_cd='FpGyZy6kld9R2XTjqvBQN')
        prospect_email.body_text = (
            'Hi {recipient_first_name}, {line_break}'
            'Thank you for your order! {line_break}'
            'ORDER INFORMATION {short_line_break}{order_information} {short_line_break}'
            'View your order here: {ENVIRONMENT_DOMAIN}/account/order?identifier={identifier}&em_cd={em_cd}&pr_cd={pr_cd} {line_break}'
            'PRODUCTS {short_line_break}{product_information} {line_break}'
            'SHIPPING METHOD {short_line_break}{shipping_information} {line_break}'
            'ORDER TOTAL {short_line_break}{order_total_information} {line_break}'
            'SHIPPING ADDRESS {short_line_break}{shipping_address_information} {line_break}'
            'BILLING ADDRESS {short_line_break}{billing_address_information} {line_break}'
            'PAYMENT INFORMATION {short_line_break}{payment_information} {line_break}'
            'Note: If you did NOT place an order at {ENVIRONMENT_DOMAIN}, do not click on the link. '
            'Instead, please forward this notification to contact@startupwebapp.com and let us know '
            'that you did not place this order and we\'ll dig in further to figure out what is going on. {line_break}'
            'We\'ll send you further emails with updates on your order along with shipping tracking '
            'information once it\'s available. {line_break}'
            'Thank you for being part of the StartUp Web App community! {line_break}'
            'By placing this order you agreed to the StartUpWebApp.com Terms of Sale: '
            '{ENVIRONMENT_DOMAIN}/terms-of-sale {line_break}'
            '© 2018 StartUp Web App LLC, All rights reserved. {line_break}'
            '{prosepct_email_unsubscribe_str}'
        )
        prospect_email.save()
        print(f"Fixed prospect email template: {prospect_email.em_cd}")
    except Email.DoesNotExist:
        print("Prospect email template not found, skipping fix.")


def reverse_fix(apps, schema_editor):
    """Reverse migration - no-op since we don't want to break the emails again."""
    print("Reverse migration for email template fix is not implemented.")


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_discount_from_email_templates'),
    ]

    operations = [
        migrations.RunPython(fix_email_templates, reverse_fix),
    ]
