version: 0.0
os: linux
files:
  - source: /StartupWebApp/StartupWebApp
    destination: /home/ec2-user/swa/django/StartupWebApp/StartupWebApp
  - source: /StartupWebApp/user
    destination: /home/ec2-user/swa/django/StartupWebApp/user
  - source: /StartupWebApp/clientevent
    destination: /home/ec2-user/swa/django/StartupWebApp/clientevent
  - source: /StartupWebApp/order
    destination: /home/ec2-user/swa/django/StartupWebApp/order
  - source: /StartupWebApp/templates
    destination: /home/ec2-user/swa/django/StartupWebApp/templates
  - source: /StartupWebApp/manage.py
    destination: /home/ec2-user/swa/django/StartupWebApp
hooks:
   ValidateService:
     - location: /scripts/ReloadUwsgiVassels.sh
       timeout: 60
       runas: ec2-user