version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-west-2"

    SETTINGS_SECRET_SRC: |
      SECRET_KEY = 'uM*&23jbOIYQEF98u2h4kfnbPIe8yXrCTqmOS0gMnX'

      ALLOWED_HOSTS = ['localapi.startupwebapp.com', 'localliveservertestcaseapi.startupwebapp.com']

      SESSION_COOKIE_SECURE = False
      SESSION_COOKIE_DOMAIN = "localapi.startupwebapp.com"

      CSRF_COOKIE_SECURE = False
      CSRF_TRUSTED_ORIGINS = "localhost.startupwebapp.com"

      DEBUG = True

      ENVIRONMENT_DOMAIN = 'http://localhost.startupwebapp.com'

      EMAIL_HOST_USER = 'AKIAJOVIUIENKNYU56ZA'
      EMAIL_HOST_PASSWORD = 'BBlkKh47UslsZxbarkx666TSC7wkpYMLCZXdsxwxsck4'

      DATABASES = {
          'default': {
              'ENGINE': 'django.db.backends.sqlite3',
              'NAME': 'swa_unittest',
              'USER': 'django_unittest',
              'PASSWORD': 'imatester',
              'HOST': '127.0.0.1',
          }
      }

      S3_QR_IMAGE_BUCKET_PATH = 'food/qr/local/'
      S3_ORDER_PDF_BUCKET_PATH = 'pdf/local/'
      S3_FOOD_IMAGE_BUCKET_PATH = 'food/main/local/'

      STRIPE_SERVER_SECRET_KEY = 'sk_test_O9l7Y5jpB3OpYQrtinEwjYhB'
      STRIPE_PUBLISHABLE_SECRET_KEY = 'pk_test_9dMmGoPijqBpKLrIX4hq8XAG'
      STRIPE_LOG_LEVEL = 'debug'

      # CORS Config
      CORS_ORIGIN_WHITELIST = (
          'localliveservertestcase.startupwebapp.com',
          'localhost.startupwebapp.com',
      )

phases:
  install:
    commands:
      - django-admin --version
  pre_build:
    commands:
      # setup django test app
      - cd $CODEBUILD_SRC_DIR
      - cd StartupWebApp/StartupWebApp
      - echo "$SETTINGS_SECRET_SRC" > settings_secret.py
      
  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - cd StartupWebApp

      # coverage test
      - coverage run --source='.' manage.py test StartupWebApp
      - coverage report --fail-under=25

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
