"""
Django settings for StartupWebApp project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# get secret settings
from .settings_secret import *

# apply settings after getting secrets

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False #override in secrets for local ONLY

CSRF_COOKIE_SECURE = True #override in secrets for local ONLY

# get secret settings again for overrides
from .settings_secret import *

#ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'order.apps.OrderConfig',
    'user.apps.UserConfig',
    'clientevent.apps.ClienteventConfig',
    'corsheaders',    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Config
CORS_ALLOW_CREDENTIALS = True

#SESSION_COOKIE_DOMAIN = ".startupwebapp.com" # set in settings_secret.py by environment
CSRF_COOKIE_DOMAIN = ".startupwebapp.com" # Leave here because this needs to be picked up by both the api sub domain and the static client domain
#CSRF_TRUSTED_ORIGINS = ".startupwebapp.com" # set in settings_secret.py by environment
#CSRF_COOKIE_AGE = 300  # 5 minutes, in seconds default is 31449600 or 1 year

SESSION_COOKIE_AGE = 1209600  # 2 weeks, in seconds
#SESSION_COOKIE_AGE = 300  # 5 minutes, in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

LOGIN_URL = "/login"
LOGOUT_REDIRECT_URL = "/"

ROOT_URLCONF = 'StartupWebApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'StartupWebApp.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
