"""
Django settings for StartupWebApp project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# get secret settings
from .settings_secret import *  # noqa: F403,F401

# apply settings after getting secrets

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False #override in secrets for local ONLY

CSRF_COOKIE_SECURE = True #override in secrets for local ONLY

# get secret settings again for overrides
from .settings_secret import *  # noqa: F403,F401,F811

# Django 4.0+ compatibility: Convert CSRF_TRUSTED_ORIGINS from old string format to new list format
# In Django 4.0+, CSRF_TRUSTED_ORIGINS must be a list with schemes (http:// or https://)
# Old format: CSRF_TRUSTED_ORIGINS = ".startupwebapp.com"
# New format: CSRF_TRUSTED_ORIGINS = ['https://*.startupwebapp.com', 'http://localhost:8080', 'http://localhost:8000']
if 'CSRF_TRUSTED_ORIGINS' in globals():  # noqa: F405
    if isinstance(CSRF_TRUSTED_ORIGINS, str):  # noqa: F405
        # Convert old string format to new list format
        old_origin = CSRF_TRUSTED_ORIGINS  # noqa: F405
        if DEBUG:
            # Development: use http for localhost
            CSRF_TRUSTED_ORIGINS = [
                'http://localhost:8080',
                'http://localhost:8000',
                'http://localhost',
            ]
        else:
            # Production: use https with wildcard subdomain
            CSRF_TRUSTED_ORIGINS = [
                f'https://*{old_origin}',
                f'https://{old_origin.lstrip(".")}',
            ]

#ALLOWED_HOSTS = []

# Security settings for production
# These settings are only applied when DEBUG=False (production environment)
# For local development, DEBUG=True in settings_secret.py overrides these
if not DEBUG:
    # HTTPS/SSL Settings
    SECURE_SSL_REDIRECT = True  # Redirect all HTTP to HTTPS
    SESSION_COOKIE_SECURE = True  # Only send session cookies over HTTPS
    CSRF_COOKIE_SECURE = True  # Only send CSRF cookies over HTTPS

    # HTTP Strict Transport Security (HSTS)
    # Tells browsers to only use HTTPS for this site for 1 year
    SECURE_HSTS_SECONDS = 31536000  # 1 year in seconds
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply to all subdomains
    SECURE_HSTS_PRELOAD = True  # Allow inclusion in browser HSTS preload lists

    # Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME-type sniffing
    SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS filtering
    X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking by denying framing

# Django 3.2+ setting: Use AutoField for primary keys (maintains backward compatibility)
# This prevents Django from creating new migrations for BigAutoField
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Application definition

INSTALLED_APPS = [
    'order.apps.OrderConfig',
    'user.apps.UserConfig',
    'clientevent.apps.ClienteventConfig',
    'corsheaders',    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Config
CORS_ALLOW_CREDENTIALS = True

#SESSION_COOKIE_DOMAIN = ".startupwebapp.com" # set in settings_secret.py by environment
#CSRF_TRUSTED_ORIGINS = ".startupwebapp.com" # set in settings_secret.py by environment
#CSRF_COOKIE_AGE = 300  # 5 minutes, in seconds default is 31449600 or 1 year

# CSRF Cookie Domain - only set for production
# In production, this allows cookies to be shared between api.startupwebapp.com and www.startupwebapp.com
# In development (DEBUG=True), leaving this unset allows cookies to work with localhost
if not DEBUG:
    CSRF_COOKIE_DOMAIN = ".startupwebapp.com"

SESSION_COOKIE_AGE = 1209600  # 2 weeks, in seconds
#SESSION_COOKIE_AGE = 300  # 5 minutes, in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

LOGIN_URL = "/login"
LOGOUT_REDIRECT_URL = "/"

ROOT_URLCONF = 'StartupWebApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'StartupWebApp.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
