# Generated by Django 2.2 on 2019-04-22 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_client_events', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clientevent_configuration',
            },
        ),
        migrations.CreateModel(
            name='Pageview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=1000)),
                ('page_width', models.IntegerField(blank=True, null=True)),
                ('remote_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('http_user_agent', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_date_time', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientevent_pageview',
            },
        ),
        migrations.CreateModel(
            name='Linkevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=1000)),
                ('created_date_time', models.DateTimeField()),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Ad')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Email')),
                ('prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Prospect')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientevent_linkevent',
            },
        ),
        migrations.CreateModel(
            name='Buttonclick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=1000)),
                ('button_id', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientevent_button_click',
            },
        ),
        migrations.CreateModel(
            name='AJAXError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=1000)),
                ('error_id', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientevent_ajax_error',
            },
        ),
    ]
