# Generated by Django 2.2.28 on 2025-11-06 02:23

from django.db import migrations


def create_default_inventory_statuses(apps, schema_editor):
    """
    Create default Skuinventory records required by the application.

    These inventory statuses are referenced by SKUs and are required
    for the product detail endpoint to function correctly.

    Based on db_inserts.sql line 12.

    This migration is skipped during test runs to allow tests to create
    their own test data without conflicts.
    """
    # Skip this migration during test runs
    # Test databases use in-memory SQLite (contains 'memory' in NAME)
    # PostgreSQL test databases start with 'test_' (e.g., test_startupwebapp_dev)
    # Development uses file-based SQLite (NAME = 'rg_unittest' or 'startupwebapp_dev')
    db_name = schema_editor.connection.settings_dict.get('NAME', '')
    if 'memory' in db_name.lower() or db_name.startswith('test_'):
        return

    Skuinventory = apps.get_model('order', 'Skuinventory')

    # Define default inventory statuses from db_inserts.sql
    default_statuses = [
        {
            'id': 1,
            'title': 'In Stock',
            'identifier': 'in-stock',
            'description': 'In Stock items are available to purchase.'
        },
        {
            'id': 2,
            'title': 'Back Ordered',
            'identifier': 'back-ordered',
            'description': 'Back Ordered items are not available to purchase at this time.'
        },
        {
            'id': 3,
            'title': 'Out of Stock',
            'identifier': 'out-of-stock',
            'description': 'Out of Stock items are not available to purchase.'
        },
    ]

    # Create inventory statuses if they don't exist
    for status_data in default_statuses:
        Skuinventory.objects.get_or_create(
            id=status_data['id'],
            defaults={
                'title': status_data['title'],
                'identifier': status_data['identifier'],
                'description': status_data['description']
            }
        )


def reverse_create_default_inventory_statuses(apps, schema_editor):
    """
    Reverse migration - delete default inventory statuses only if safe.

    This only deletes statuses that are not referenced by any SKUs,
    ensuring data integrity.
    """
    Skuinventory = apps.get_model('order', 'Skuinventory')

    default_ids = [1, 2, 3]

    for status_id in default_ids:
        try:
            status = Skuinventory.objects.get(id=status_id)
            # Check if any SKUs reference this status
            # Note: We can't use reverse relations in data migrations,
            # so we'll just delete and let CASCADE handle it
            if status.sku_set.count() == 0:
                status.delete()
        except Skuinventory.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_default_inventory_statuses,
            reverse_create_default_inventory_statuses
        ),
    ]
