# Generated by Django 4.2.16 on 2025-12-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_seed_order_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
