# Generated by Django 5.2.9 on 2025-12-30 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderpayment_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderemailfailure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_type', models.CharField(choices=[('template_lookup', 'Email template not found'), ('formatting', 'Email body formatting failed'), ('smtp_send', 'SMTP email sending failed'), ('emailsent_log', 'Emailsent record creation failed'), ('cart_delete', 'Cart deletion failed')], max_length=50)),
                ('error_message', models.TextField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('is_member_order', models.BooleanField(default=False)),
                ('phase', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_date_time', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'order_order_email_failure',
                'indexes': [models.Index(fields=['resolved', 'created_date_time'], name='idx_resolved_created'), models.Index(fields=['order'], name='idx_order'), models.Index(fields=['customer_email'], name='idx_customer_email')],
            },
        ),
    ]
