# Generated by Django 5.2.9 on 2026-01-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderemailfailure'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersku',
            name='discounted_price_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersku',
            name='original_price_cents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
