# Generated by Django 5.2.9 on 2026-01-22 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordersku_discounted_price_cents_and_more'),
    ]

    operations = [
        # Remove fields from Order model
        migrations.RemoveField(
            model_name='order',
            name='item_discount_amt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_discount_amt',
        ),

        # Delete discount-related models (order matters - delete dependent models first)
        migrations.DeleteModel(
            name='Orderdiscount',
        ),
        migrations.DeleteModel(
            name='Cartdiscount',
        ),
        migrations.DeleteModel(
            name='Discountcode',
        ),
        migrations.DeleteModel(
            name='Discounttype',
        ),
    ]
